pipeline:
  test:
    image: maven:3-jdk-8-slim
    commands: 
      - mvn clean test -B -Dmaven.repo.local=./m2

  deploy_snapshot:
    image: maven:3-jdk-8-slim
    secrets: [m2_settings]
    commands:
      - echo $M2_SETTINGS > $HOME/.m2/settings.xml
      - mvn install -B -Pwith-sources,with-javadoc,deploy-pom-nexus -Dmaven.repo.local=./m2
    when:
      branch: master
      event: push

  deploy_release:
    image: maven:3-jdk-8-slim
    secrets: [m2_settings]
    commands:
      - echo $M2_SETTINGS > $HOME/.m2/settings.xml
      - mvn install -B -Pwith-sources,with-javadoc,deploy-pom-nexus-release -Dmaven.repo.local=./m2
    when:
      branch: [release/*]
      event: deployment
      environment: releases
